kind: pipeline
type: docker
name: test

steps:
  - name: Test Homebrew
    image: homebrew/brew:latest
    commands:
      - ./test.sh
node:  # Homebrew only has amd64 images so must run on amd64 platforms
  host: albertyw-server
