kind: pipeline
type: docker
name: test

steps:
  - name: Test Homebrew
    image: homebrew/brew:3.1.12
    commands:
      - brew audit ./git-browse.rb
      - brew audit ./git-reviewers.rb
      - brew test ./git-browse.rb
      - brew test ./git-reviewers.rb
